### PR TITLE
Add a semantic versioning checker

### PR DESCRIPTION
**Pull request by Luni-4**
### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

A semantic versioning checker lints API changes for semver violations. Even this check will run periodically on CI not to stress a lot the entire infrastracture

### CODE REVIEW

**Comment by Luni-4** [comment]
I tried to cross-compile `metal' on `Linux` but it is not possible as stated [here](https://github.com/gfx-rs/metal-rs?tab=readme-ov-file#documentation). How can I disable that compilation? Is there a way to automatically **not** enable the compilation on a system different from `MacOs` or I have to use `DISABLE_WGPU` environment variable?

**Comment by Luni-4** [comment]
Ok, fixed everything

**Comment by syl20bnr** [comment]
Thank you, that's a valuable check to have. Do we want to activate it before we hit the `1.0` mark ? Or is this action smart enough to understand projects in `0.x` ?

**Comment by Luni-4** [comment]
It should work, it uses the same `vulnerabilities.yml` semantic and that actions run https://github.com/tracel-ai/burn/actions/runs/7731579136 when we published `0.12` version.

**Review by syl20bnr — APPROVED** [review]
Let's try this one, thank you 👍🏻

**Review by nathanielsimard — COMMENTED** [review]
I'm not sure if this is a valuable check for us, since every release will be a breaking change until v1.0. Adding a check for patches seems a bit too much in term of process.

What do you think @antimora @syl20bnr ?

**Comment by antimora** [comment]
> I'm not sure if this is a valuable check for us, since every release will be a breaking change until v1.0. Adding a check for patches seems a bit too much in term of process.
> 
> What do you think @antimora @syl20bnr ?

Probably the value to know what APIs are breaking. From [the docs](https://github.com/obi1kenobi/cargo-semver-checks-action), it appears it's use before a publish operation. 

I think it's also useful once we go 1.0. So it might be useful to get accustomed.

**Review by antimora — APPROVED** [review]

**Comment by Luni-4** [comment]
> I'm not sure if this is a valuable check for us, since every release will be a breaking change until v1.0. Adding a check for patches seems a bit too much in term of process.
> 
> What do you think @antimora @syl20bnr ?

Actually it runs perfectly comparing `0.12.` and `0.11.1`, so we can use that before `1.0`. I agree with @antimora about getting accustomed, and yep, it runs **before** a publish operation

**Comment by nathanielsimard** [comment]
Ok then, let's try it!

**Pull request merged**
