### PR TITLE
chore(web): better panic 

### PR DESCRIPTION
**Pull request by dcvz**
### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Changes

Provides better panic support on web to help debug issues like #1034

### CODE REVIEW

**Review by antimora — APPROVED** [review]
Ahhh super! that's what we were missing!

**Comment by AlexErrant** [comment]
You might consider using [start](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/start.html). I do so [here](https://github.com/tracel-ai/burn/pull/938/files#diff-481b91772c3f0745e1e4ea6c9ab49705889638cb8f56832207dec6ad13154538R13-R17).

**Comment by dcvz** [comment]
> here

Done! I considered it, but we already had a start point so thought that'd be fine. Updated to be more proper.

**Comment by dcvz** [comment]
@antimora @nathanielsimard should be good to go now!

**Pull request merged**
