### PR TITLE
Use AsRef<Path> instead of &str for file operations

### PR DESCRIPTION
**Pull request by ivnsch**
### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

https://github.com/tracel-ai/burn/issues/698

### Changes

Replaced all file related `&str` with `AsRef<Path>`

Exception: https://github.com/tracel-ai/burn/blob/main/crates/burn-import/src/burn/graph.rs#L347
This generates code, where `std::path::Path` can be added, but std is not available.
Also not sure whether e.g. [here](https://github.com/ivnsch/burn/blob/replace_str_with_as_ref/examples/guide/src/inference.rs#L10) the order of the type variables is correct, should it match the order of the parameters, or just be appended (current)?

Some calls got slightly noisier, but not necessarily an issue https://github.com/ivnsch/burn/blob/replace_str_with_as_ref/examples/guide/src/bin/infer.rs#L13

Anyway, just opening the PR and waiting for feedback.

### Testing

I ran `./run-checks.sh all` and `cargo test`. `cargo test` is currently not helping much, because of all the cuda errors (don't have nvidia and not sure how to exclude them).

These changes seem unlikely to affect the book, but can review it once this has received some feedback.

### CODE REVIEW

**Review by laggui — COMMENTED** [review]
Thanks for taking a look at the issues!

I think the intention from the linked issue was for the user facing APIs. IMO the usage for strings/slices doesn't need to be changed for *everything* in the repo (such as examples, or stuff that is not user facing).

>  Also not sure whether e.g. [here](https://github.com/ivnsch/burn/blob/replace_str_with_as_ref/examples/guide/src/inference.rs#L10) the order of the type variables is correct, should it match the order of the parameters, or just be appended (current)?

I don't think the order matters that much. Usually it follows the arguments but that's just because most people add the generics as they read from left to right, following the order of the args. So it wouldn't matter really in this case, but anyway I wouldn't necessarily change the code in the examples as it is.

**Comment by ivnsch** [comment]
Ok, the majority of the changes are in examples, except a test ([burn-core/tests/test_derive_config.rs](https://github.com/ivnsch/burn/blob/replace_str_with_as_ref/crates/burn-core/tests/test_derive_config.rs#L30)) and `burn-fork/crates/burn-import/src/onnx/to_burn.rs` [change 1](https://github.com/ivnsch/burn/blob/replace_str_with_as_ref/crates/burn-import/src/onnx/to_burn.rs#L105), [change 2](https://github.com/ivnsch/burn/blob/replace_str_with_as_ref/crates/burn-import/src/onnx/to_burn.rs#L111). Would these be user facing? not very familiar with the project yet.

**Comment by laggui** [comment]
These changes are also not user facing 🙂

Now that I went back and read the linked issue, it seems that the specific example provided (for the `Config` trait methods) has already been addressed in #699.

And even more changes have been made in #1919. I think the issue was mistakenly not closed since it was not directly linked as fixed in these PRs.

**Comment by ivnsch** [comment]
Alright, closing this then!

**Pull request closed without merging**
