### PR TITLE
Deprecate the use of std::collections::HashMap

### PR DESCRIPTION
**Pull request by nakashima-hikaru**
### Checklist

- [X] Confirmed that `run-checks all` script has been executed.
- [X] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

_Provide links to relevant issues and dependent PRs._

### Changes

Replace std::collections::HashMap and std::collections::HashSet to hashbrown.

### Testing

_Describe how these changes have been tested._

### CODE REVIEW

**Comment by antimora** [comment]
What's a rational for this big change?

**Comment by Arjun31415** [comment]
Hashmap uses the same algorithm as HashBrown since rust 1.36, I feel there is no need to "deprecate" it. 
Furthermore the README of hashbrown says so (the only incentive is hashbrown works in no_std environment)
https://github.com/rust-lang/hashbrown

**Comment by Luni-4** [comment]
@Arjun31415 

Do you think we could use [heapless](https://docs.rs/heapless/latest/heapless/) in some places for `no_std` environment? In this way we would have a static allocation instead of a dynamic one. It would be a restrictive choices though, because with `hashbrown` you can choose the allocator

**Comment by Arjun31415** [comment]
I do not understand the reason for it though ? Is it because using the current hashmap is causing some slowdown ?. 
Also, by just reading the introduction docs of heapless, we would have to handle the case where the container grows beyond its capacity ourselves right?

**Comment by Luni-4** [comment]
Your analysis is correct, I would like to understand if it's possible to use `heapless` for some contexts

**Comment by nakashima-hikaru** [comment]
> Hashmap uses the same algorithm as HashBrown since rust 1.36, I feel there is no need to "deprecate" it. Furthermore the README of hashbrown says so (the only incentive is hashbrown works in no_std environment) https://github.com/rust-lang/hashbrown

Sorry, my misunderstanding.
When I looked at https://github.com/pola-rs/polars, I found that std::collections::HashMap and std::collections::HashSet are prohibited.
So I misunderstood that the algorithm of hashbrown should be used instead of std::collections.

**Comment by Arjun31415** [comment]
> Your analysis is correct, I would like to understand if it's possible to use `heapless` for some contexts

I'm not sure, better to ask others.

**Comment by antimora** [comment]
We already use hashbrown for no-std. We conditionally swap during a build. 

Heapless is not necessary because we need heap alloc (string, vec, etc)

**Pull request closed without merging**
