### PR TITLE
feat: adding shape support for gather ONNX operation

### PR DESCRIPTION
**Pull request by mepatrick73**
### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

#2115

### Changes

_Summarize the problem being addressed and your solution._

### Testing

_Describe how these changes have been tested._

### CODE REVIEW

**Comment by mepatrick73** [comment]
I've resolved the user's issue. There's a section of code that checks if the rank of the indices tensor is greater than 1, and if so, it triggers a panic. This check seems unnecessary since the underlying gather operation in Burn supports multi-dimensional tensors (though I might be mistaken). The user's model uses a multi-dimensional indices tensor, causing a crash before completing the parsing of the Gather node. If I remove this check, the operation graph progresses further. Should I remove the indices_dim check?

**Comment by laggui** [comment]
> I've resolved the user's issue. There's a section of code that checks if the rank of the indices tensor is greater than 1, and if so, it triggers a panic. This check seems unnecessary since the underlying gather operation in Burn supports multi-dimensional tensors (though I might be mistaken). The user's model uses a multi-dimensional indices tensor, causing a crash before completing the parsing of the Gather node. If I remove this check, the operation graph progresses further. Should I remove the indices_dim check?

If you check the code, the ONNX Gather op actually translates to `tensor.select(dim, indices)`. There is another ONNX op called GatherElements which corresponds to burn's gather operation on a tensor.

So the rank 1 tensor limitation is because `select` only accepts 1d indices.

Linking the original gather PR #1843  for reference.

**Comment by laggui** [comment]
@mepatrick73 this is ready for review right? The changes look good to me w.r.t supporting shape input.

**Comment by antimora** [comment]
Looks good to me so far

**Comment by hexd0t** [comment]
When Gathering from a `Shape`, shouldn't the output also be an `ArgType::Shape` instead of converting it to a `Tensor`?

**Comment by mepatrick73** [comment]
The rank of the output tensor could be bigger than 1, therefore Shape is not appropriate.

**Comment by mepatrick73** [comment]
> @mepatrick73 this is ready for review right? The changes look good to me w.r.t supporting shape input.

Yes it is ready for review :)

**Review by laggui — APPROVED** [review]
Thanks for fixing the shape support 🙏

**Pull request merged**
