### PR TITLE
Implementing ONNX support for sqrt

### PR DESCRIPTION
**Pull request by edmondop**
## Pull Request Template

Addresses #600  SQRT operator.

ONNX validity has been confirmed using Neutron, see
sqrt onnx

### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Testing

`cargo test` in the `burn-import` subpackage

### CODE REVIEW

**Review by antimora — CHANGES_REQUESTED** [review]
Looks great! 

One small change requested in the supported ops: to replace X with a check mark:

https://github.com/Tracel-AI/burn/blob/main/burn-import/SUPPORTED-ONNX-OPS.md?plain=1#L181

Once this is done, it's approved.

**Comment by edmondop** [comment]
> Looks great!
> 
> One small change requested in the supported ops: to replace X with a check mark:
> 
> [`main`/burn-import/SUPPORTED-ONNX-OPS.md?plain=1#L181](https://github.com/Tracel-AI/burn/blob/main/burn-import/SUPPORTED-ONNX-OPS.md?plain=1&rgh-link-date=2023-11-22T21%3A14%3A28Z#L181)
> 
> Once this is done, it's approved.

Fixed with https://github.com/Tracel-AI/burn/pull/991/commits/02b3ecb1148233354c7b03ed1082acd13bcd3643

**Review by antimora — APPROVED** [review]
Approved! 

Thank you for your contribution!

**Comment by antimora** [comment]
All green. Thank you for your contribution!

**Pull request merged**
