### PR TITLE
[refactor] Move burn crates to their own crates directory

### PR DESCRIPTION
**Pull request by syl20bnr**
### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

Fixes https://github.com/tracel-ai/burn/issues/1263

### Changes

Move all the burn crates to their dedicated directory called `crates`.
We chose to keep the crate folder names to be the same as the actual crate name, see discussed in https://github.com/tracel-ai/burn/issues/1263

I'll update the links in the contributor book once this is merged.

### Testing

`run-checks` and making sure our CI passes.

### CODE REVIEW

**Comment by Luni-4** [comment]
Fantastic! Perhaps we can add

```toml
members = [
  "crates/*",
]
```

to the main `Cargo.toml`.

I was wondering if it would be clearer to move  `examples` crates, since they are independent, into a new `burn` repository such as the `models` repository.

**Comment by syl20bnr** [comment]
I updated the Cargo file with `crates/*`. 👍

We have no mechanism to publish examples alongside versions and they are using local crates from the repo. So for now it is better to keep them in the monorepo.

**Comment by antimora** [comment]
> Fantastic! Perhaps we can add
> 
> ```toml
> members = [
>   "crates/*",
> ]
> ```
> 
> to the main `Cargo.toml` instead of each single crate
> 
> I was wondering if it would be clearer to move `examples` crates, since they are independent, into a new `burn` repository such as the `models` repository.

I would add we should keep in the same repository. It would be difficult to synchronize the versions

**Comment by Luni-4** [comment]
To synchronize the versions we just have to change from `path` to `git` since they do not have to be published it should not be problematic

**Review by Luni-4 — APPROVED** [review]

**Pull request merged**
