### PR TITLE
Support for scalar optimization

### PR DESCRIPTION
**Pull request by carrotflakes**
### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

_Provide links to relevant issues and dependent PRs._

### Changes

I encountered an error when attempting to optimize scalars (`Param<Tensor<B, 0>>`). The issue stemmed from the absence of `AdaptorRecordV1::Rank0` . This was likely an oversight, so I added `Rank0` support.

### Testing

I confirmed that it is possible to train my model that include `Param<Tensor<B, 0>>`.

### CODE REVIEW

**Comment by carrotflakes** [comment]
The test is failing, but I don't think the change is the cause.
Is there anything I can do to fix the test?
Also, is there something missing in this pull request?

**Comment by antimora** [comment]
CI is failing due to this error in WGPU backend, which could be a fluke. I will re-run the CI again. Meanwhile I am tagging @nathanielsimard and @louisfd:

```
 test tests::jit_fusion::var::tests::test_var_mean_bias ... ok
  
  failures:
  
  ---- tests::jit::kernel::reduction::reduction::reduction_sum_dim_should_work_with_multiple_invocations stdout ----
  thread 'tests::jit::kernel::reduction::reduction::reduction_sum_dim_should_work_with_multiple_invocations' panicked at crates/burn-wgpu/src/lib.rs:73:5:
  Tensors are not approx eq:
    => Position 1: 507.8968200683594 != 507.8955383300781 | difference 0.00128173828125 > tolerance 0.0010000000000000002
  
  
  failures:
      tests::jit::kernel::reduction::reduction::reduction_sum_dim_should_work_with_multiple_invocations
  
  test result: FAILED. 1341 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 50.05s
  
  error: test failed, to rerun pass `-p burn-wgpu --lib`
  Error: Process completed with exit code 101.

```

**Comment by louisfd** [comment]
This test's tolerance was changed from 10e-3 to 10e-2 since the creation of this PR. By merging main into your branch you should be fine.

**Comment by carrotflakes** [comment]
Thank you! merged.

**Review by nathanielsimard — APPROVED** [review]

**Pull request merged**
