### PR TITLE
Docs/tensor basic ops

### PR DESCRIPTION
**Pull request by quinton11**
### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs
#2450 

_Provide links to relevant issues and dependent PRs._

### Changes
Tensor BasicOps Examples

### CODE REVIEW

**Comment by quinton11** [comment]
@laggui @nathanielsimard

**Review by laggui — CHANGES_REQUESTED** [review]
Thanks for working on the examples 🙏 

Just a few comments to get this started:
- Make sure to run the tests for formatting and ensure the doc examples can compile (see CI errors)
- I see some methods have more than one example. I think we should keep the examples succinct, so stick to one `example()` definition (though you could still demonstrate different manipulations when deemed relevant)

**Comment by quinton11** [comment]
@laggui made the necessary changes, as well as a fix for the failing doc examples

**Review by laggui — APPROVED** [review]
LGTM!

Made some minor changes mostly for formatting.

**Pull request merged**
