### PR TITLE
Support signed value for `Tensor::arange`

### PR DESCRIPTION
**Pull request by Nikaidou-Shinku**
### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

#1234

### Changes

Make `Tensor::arange` and all internal methods accept a `Range<i64>` instead of `Range<usize>` to support ranges of signed value.

### Testing

`bash ./run-checks.sh all` was passed.

### CODE REVIEW

**Review by antimora — CHANGES_REQUESTED** [review]
1. A new unit test should be added to test all new edge cases (negatives and 0, overflow range). 

2. Extra caution when casting usize to i64 because it overflow.

**Comment by nathanielsimard** [comment]
> 1. A new unit test should be added to test all new edge cases (negatives and 0, overflow range).
> 2. Extra caution when casting usize to i64 because it overflow.

I think we should check if we can replace the usize by i64 instead of casting in most places.

**Comment by Nikaidou-Shinku** [comment]
I moved the functions about arange to `int_tensor.rs`, and add some test cases for 0 and negative numbers.
Regarding overflow, I don't have any good ideas. I noticed that for most cases where arange is used in the test cases, the range is taken from the shape of tensors. In this case, when an overflow occurs, I don't know what else to do but crash the program.

**Review by nathanielsimard — APPROVED** [review]

**Review by antimora — APPROVED** [review]
LGTM

**Pull request merged**
