### PR TITLE
Add ReduceProd ONNX Import

### PR DESCRIPTION
**Pull request by Dirleye**
### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

#1894, #1714

### Changes

Adds support for ONNX ReduceProd burn-import in an attempt to understand the structure better.

### Testing

`cargo test -p burn-import`
`cargo test -p onnx-tests`

### CODE REVIEW

**Comment by Dirleye** [comment]
Hi there, hopefully this is all correct. Most seems to be very similar to the other reduce ops anyway.

onnx-tests is currently failing with `900.0001 != 900`, probably just due to floating point multiplication shenanigans. Does anyone have some advice as to how to go about this problem?

**Comment by antimora** [comment]
> Hi there, hopefully this is all correct. Most seems to be very similar to the other reduce ops anyway.
> 
> onnx-tests is currently failing with `900.0001 != 900`, probably just due to floating point multiplication shenanigans. Does anyone have some advice as to how to go about this problem?

You can change precision in assertion. 

Currently, however, it's failing to due missing comma in generated code:


image

**Comment by Dirleye** [comment]
Should be better now.
`run-checks all` is failing at `tests::jit::remainder::tests::should_be_zero` but it's failing on main as well for me so it looks to be unrelated to this PR?

**Review by laggui — APPROVED** [review]
LGTM! I was just reviewing the PR and your last commit addressed the comments I had.

Thank you 🙏

**Pull request merged**
