### PR TITLE
Fix checks_channels_div_groups condition and ONNX conv import with groups

### LINKED ISSUE #2043: Strange model initialization errors
There are a couple of strange errors that I am see when I load Face ONNX and what to just instantiate a model. 

These errors can be reproduced in this repo: https://github.com/antimora/face-onnx

By running:

```
cargo run --bin with_weights
```

Which will result in this error:

```
Uniform::new called with `low` non-finite.
```

and 

```
cargo run --bin without_weights
```

Which will result in this error:
```
cast_slice>PodCastError(TargetAlignmentGreaterAndInputNotAligned)
```

### PR DESCRIPTION
**Pull request by laggui**
### Checklist

- [x] Confirmed that `run-checks all` script has been executed.

### Related Issues/PRs

Closes #2043 

### Changes

The check condition was not actually checking for both values to be divisible, so I fixed the condition.

### Testing

Added a unit test.

### CODE REVIEW

**Comment by laggui** [comment]
Huh, conv transpose tests are failing in burn-import. But it looks like the values are incorrectly converted.

For example, the `conv_transpose2d` test fails with:
```
Both channels must be divisible by the number of groups. Got channels_in=3, channels_out=4, groups=2
```

but the node actually defines `channels_in=4`, `channels_out=6`. I think there might be a bug there.

**Comment by laggui** [comment]
Turns out the groups weren't taken into account when importing the ONNX models 🙂everything should be fixed now.

**Comment by laggui** [comment]
Still seems to be an issue when trying to import the model from the linked issue. Trying to fix it right now.

**Review by antimora — APPROVED** [review]
LGTM!

Thanks for fixing it!

**Pull request merged**
