### PR TITLE
Fix candle backend sync

### PR DESCRIPTION
**Pull request by nathanielsimard**
I would lead to wrong benchmark times for the CUDA and Metal backends of Candle.

### CODE REVIEW

**Review by louisfd — APPROVED** [review]
lgtm

**Review by dcvz — APPROVED** [review]
LGTM 👍 CI is failing for a timeout, should pass on rerun

**Comment by nathanielsimard** [comment]
I'm unsure if this fixes the problem on Metal, we have to do more testing.

**Comment by antimora** [comment]
I have tested your PR branch and ran the benchmarks. Here are the results.

```sh
[burn]% cargo run --release --bin burnbench -- run --share  --backends all --benches all
```

https://burn.dev/benchmarks/community-benchmarks?user=SolarUnerringness&os=Mac%20OS%2014%2E4%2E1%20%5B64%2Dbit%5D&version1=37e2c7b58e11c42401ca8e9a69b27fe1b239912c&version2=37e2c7b58e11c42401ca8e9a69b27fe1b239912c&search=true

| Benchmark                      | Feature                 | Backend                 | Device        | Median         |
|--------------------------------|-------------------------|-------------------------|---------------|----------------|
| binary                         | candle-cpu              | `candle`                | Cpu           | 3.923ms        |
| binary                         | candle-metal            | `candle`                | Metal(0)      | 510.000µs      |
| binary                         | ndarray                 | `ndarray`               | Cpu           | 3.994ms        |
| binary                         | ndarray-blas-accelerate | `ndarray`               | Cpu           | 3.710ms        |
| binary                         | tch-cpu                 | `tch`                   | Cpu           | 2.461ms        |
| binary                         | wgpu                    | `jit<wgpu>`             | BestAvailable | 5.123ms        |
| binary                         | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 2.592ms        |
| gelu_Reference                 | candle-cpu              | `candle`                | Cpu           | 167.231ms      |
| gelu_WithReferenceErf          | candle-cpu              | `candle`                | Cpu           | 252.911ms      |
| gelu_WithCustomErf             | candle-cpu              | `candle`                | Cpu           | 604.044ms      |
| gelu_autodiff_Reference        | candle-cpu              | `candle`                | Cpu           | 791.496ms      |
| gelu_autodiff_WithReferenceErf | candle-cpu              | `candle`                | Cpu           | 615.678ms      |
| gelu_autodiff_WithCustomErf    | candle-cpu              | `candle`                | Cpu           | 1.962s         |
| gelu_Reference                 | candle-metal            | `candle`                | Metal(0)      | 520.000µs      |
| gelu_WithReferenceErf          | candle-metal            | `candle`                | Metal(0)      | 866.000µs      |
| gelu_WithCustomErf             | candle-metal            | `candle`                | Metal(0)      | 133.324ms      |
| gelu_Reference                 | ndarray                 | `ndarray`               | Cpu           | 111.040ms      |
| gelu_WithReferenceErf          | ndarray                 | `ndarray`               | Cpu           | 110.839ms      |
| gelu_WithCustomErf             | ndarray                 | `ndarray`               | Cpu           | 435.753ms      |
| gelu_autodiff_Reference        | ndarray                 | `ndarray`               | Cpu           | 664.325ms      |
| gelu_autodiff_WithReferenceErf | ndarray                 | `ndarray`               | Cpu           | 320.431ms      |
| gelu_autodiff_WithCustomErf    | ndarray                 | `ndarray`               | Cpu           | 1.556s         |
| gelu_Reference                 | ndarray-blas-accelerate | `ndarray`               | Cpu           | 110.005ms      |
| gelu_WithReferenceErf          | ndarray-blas-accelerate | `ndarray`               | Cpu           | 110.777ms      |
| gelu_WithCustomErf             | ndarray-blas-accelerate | `ndarray`               | Cpu           | 460.139ms      |
| gelu_autodiff_Reference        | ndarray-blas-accelerate | `ndarray`               | Cpu           | 658.916ms      |
| gelu_autodiff_WithReferenceErf | ndarray-blas-accelerate | `ndarray`               | Cpu           | 328.993ms      |
| gelu_autodiff_WithCustomErf    | ndarray-blas-accelerate | `ndarray`               | Cpu           | 1.590s         |
| gelu_Reference                 | tch-cpu                 | `tch`                   | Cpu           | 7.933ms        |
| gelu_WithReferenceErf          | tch-cpu                 | `tch`                   | Cpu           | 17.914ms       |
| gelu_WithCustomErf             | tch-cpu                 | `tch`                   | Cpu           | 123.529ms      |
| gelu_autodiff_Reference        | tch-cpu                 | `tch`                   | Cpu           | 33.462ms       |
| gelu_autodiff_WithReferenceErf | tch-cpu                 | `tch`                   | Cpu           | 51.253ms       |
| gelu_autodiff_WithCustomErf    | tch-cpu                 | `tch`                   | Cpu           | 356.825ms      |
| gelu_Reference                 | wgpu                    | `jit<wgpu>`             | BestAvailable | 6.459ms        |
| gelu_WithReferenceErf          | wgpu                    | `jit<wgpu>`             | BestAvailable | 6.481ms        |
| gelu_WithCustomErf             | wgpu                    | `jit<wgpu>`             | BestAvailable | 49.848ms       |
| gelu_autodiff_Reference        | wgpu                    | `jit<wgpu>`             | BestAvailable | 37.117ms       |
| gelu_autodiff_WithReferenceErf | wgpu                    | `jit<wgpu>`             | BestAvailable | 30.709ms       |
| gelu_autodiff_WithCustomErf    | wgpu                    | `jit<wgpu>`             | BestAvailable | 164.962ms      |
| gelu_Reference                 | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 2.621ms        |
| gelu_WithReferenceErf          | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 2.620ms        |
| gelu_WithCustomErf             | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 2.878ms        |
| gelu_autodiff_Reference        | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 14.227ms       |
| gelu_autodiff_WithReferenceErf | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 17.919ms       |
| gelu_autodiff_WithCustomErf    | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 83.159ms       |
| to_data                        | candle-cpu              | `candle`                | Cpu           | 1.636ms        |
| from_data                      | candle-cpu              | `candle`                | Cpu           | 6.337ms        |
| to_data                        | candle-metal            | `candle`                | Metal(0)      | 15.384ms       |
| from_data                      | candle-metal            | `candle`                | Metal(0)      | 16.246ms       |
| to_data                        | ndarray                 | `ndarray`               | Cpu           | 224.259ms      |
| from_data                      | ndarray                 | `ndarray`               | Cpu           | 5.310ms        |
| to_data                        | ndarray-blas-accelerate | `ndarray`               | Cpu           | 226.126ms      |
| from_data                      | ndarray-blas-accelerate | `ndarray`               | Cpu           | 4.568ms        |
| to_data                        | tch-cpu                 | `tch`                   | Cpu           | 2.368ms        |
| from_data                      | tch-cpu                 | `tch`                   | Cpu           | 7.319ms        |
| to_data                        | wgpu                    | `jit<wgpu>`             | BestAvailable | 14.798ms       |
| from_data                      | wgpu                    | `jit<wgpu>`             | BestAvailable | 9.344ms        |
| to_data                        | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 14.509ms       |
| from_data                      | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 9.750ms        |
| matmul                         | candle-cpu              | `candle`                | Cpu           | 15.944ms       |
| matmul                         | candle-metal            | `candle`                | Metal(0)      | 278.000µs      |
| matmul                         | ndarray                 | `ndarray`               | Cpu           | 32.946ms       |
| matmul                         | ndarray-blas-accelerate | `ndarray`               | Cpu           | 5.715ms        |
| matmul                         | tch-cpu                 | `tch`                   | Cpu           | 6.405ms        |
| matmul                         | wgpu                    | `jit<wgpu>`             | BestAvailable | 24.067ms       |
| matmul                         | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 24.142ms       |
| unary                          | candle-cpu              | `candle`                | Cpu           | 71.323ms       |
| unary                          | candle-metal            | `candle`                | Metal(0)      | 535.000µs      |
| unary                          | ndarray                 | `ndarray`               | Cpu           | 190.737ms      |
| unary                          | ndarray-blas-accelerate | `ndarray`               | Cpu           | 191.127ms      |
| unary                          | tch-cpu                 | `tch`                   | Cpu           | 7.791ms        |
| unary                          | wgpu                    | `jit<wgpu>`             | BestAvailable | 3.856ms        |
| unary                          | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 2.591ms        |
| max_pool2d                     | ndarray                 | `ndarray`               | Cpu           | 290.924ms      |
| max_pool2d                     | ndarray-blas-accelerate | `ndarray`               | Cpu           | 286.830ms      |
| max_pool2d                     | tch-cpu                 | `tch`                   | Cpu           | 295.646ms      |
| max_pool2d                     | wgpu                    | `jit<wgpu>`             | BestAvailable | 8.911ms        |
| max_pool2d                     | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 8.924ms        |
| load_record_lazy               | candle-cpu              | `candle`                | Cpu           | 2.621ms        |
| load_record_manual             | candle-cpu              | `candle`                | Cpu           | 2.583ms        |
| load_record_sync               | candle-cpu              | `candle`                | Cpu           | 307.180ms      |
| load_record_lazy               | candle-metal            | `candle`                | Metal(0)      | 1.686ms        |
| load_record_manual             | candle-metal            | `candle`                | Metal(0)      | 113.000µs      |
| load_record_sync               | candle-metal            | `candle`                | Metal(0)      | 3.603ms        |
| load_record_lazy               | ndarray                 | `ndarray`               | Cpu           | 3.068ms        |
| load_record_manual             | ndarray                 | `ndarray`               | Cpu           | 3.204ms        |
| load_record_sync               | ndarray                 | `ndarray`               | Cpu           | 492.751ms      |
| load_record_lazy               | ndarray-blas-accelerate | `ndarray`               | Cpu           | 3.095ms        |
| load_record_manual             | ndarray-blas-accelerate | `ndarray`               | Cpu           | 2.932ms        |
| load_record_sync               | ndarray-blas-accelerate | `ndarray`               | Cpu           | 493.590ms      |
| load_record_lazy               | tch-cpu                 | `tch`                   | Cpu           | 1.612ms        |
| load_record_manual             | tch-cpu                 | `tch`                   | Cpu           | 1.756ms        |
| load_record_sync               | tch-cpu                 | `tch`                   | Cpu           | 116.914ms      |
| load_record_lazy               | wgpu                    | `jit<wgpu>`             | BestAvailable | 7.000µs        |
| load_record_manual             | wgpu                    | `jit<wgpu>`             | BestAvailable | 9.000µs        |
| load_record_sync               | wgpu                    | `jit<wgpu>`             | BestAvailable | 6.202ms        |
| load_record_lazy               | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 11.000µs       |
| load_record_manual             | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 16.000µs       |
| load_record_sync               | wgpu-fusion             | `fusion<jit<wgpu>>`     | BestAvailable | 7.541ms        |
| binary                         | -                       | `candle-cuda`           | -             | FAILED         |
| binary                         | -                       | `ndarray-blas-netlib`   | -             | FAILED         |
| binary                         | -                       | `ndarray-blas-openblas` | -             | FAILED         |
| binary                         | -                       | `tch-gpu`               | -             | FAILED         |
| custom-gelu                    | -                       | `candle-cuda`           | -             | FAILED         |
| custom-gelu                    | -                       | `candle-metal`          | -             | FAILED         |
| custom-gelu                    | -                       | `ndarray-blas-netlib`   | -             | FAILED         |
| custom-gelu                    | -                       | `ndarray-blas-openblas` | -             | FAILED         |
| custom-gelu                    | -                       | `tch-gpu`               | -             | FAILED         |
| data                           | -                       | `candle-cuda`           | -             | FAILED         |
| data                           | -                       | `ndarray-blas-netlib`   | -             | FAILED         |
| data                           | -                       | `ndarray-blas-openblas` | -             | FAILED         |
| data                           | -                       | `tch-gpu`               | -             | FAILED         |
| matmul                         | -                       | `candle-cuda`           | -             | FAILED         |
| matmul                         | -                       | `ndarray-blas-netlib`   | -             | FAILED         |
| matmul                         | -                       | `ndarray-blas-openblas` | -             | FAILED         |
| matmul                         | -                       | `tch-gpu`               | -             | FAILED         |
| unary                          | -                       | `candle-cuda`           | -             | FAILED         |
| unary                          | -                       | `ndarray-blas-netlib`   | -             | FAILED         |
| unary                          | -                       | `ndarray-blas-openblas` | -             | FAILED         |
| unary                          | -                       | `tch-gpu`               | -             | FAILED         |
| max-pool2d                     | -                       | `candle-cpu`            | -             | FAILED         |
| max-pool2d                     | -                       | `candle-cuda`           | -             | FAILED         |
| max-pool2d                     | -                       | `candle-metal`          | -             | FAILED         |
| max-pool2d                     | -                       | `ndarray-blas-netlib`   | -             | FAILED         |
| max-pool2d                     | -                       | `ndarray-blas-openblas` | -             | FAILED         |
| max-pool2d                     | -                       | `tch-gpu`               | -             | FAILED         |
| load-record                    | -                       | `candle-cuda`           | -             | FAILED         |
| load-record                    | -                       | `ndarray-blas-netlib`   | -             | FAILED         |
| load-record                    | -                       | `ndarray-blas-openblas` | -             | FAILED         |
| load-record                    | -                       | `tch-gpu`               | -             | FAILED         |

**Comment by antimora** [comment]
Here is the comparison link: 
https://burn.dev/benchmarks/community-benchmarks/?version1=f548b731787a3ad29e756fb31a5d44de9bbf181a&versionLabel1=Version+1&version2=37e2c7b58e11c42401ca8e9a69b27fe1b239912c&versionLabel2=Version+2&backend=All&device=All&name=All&os=Mac+OS+14.4.1+%5B64-bit%5D&sysHardware=Any&user=SolarUnerringness&search=true

**Comment by nathanielsimard** [comment]
@antimora I don't think it actually fixed the benchmarks. The times were way too fast on Metal (Like the matrix multiplication is still 10x faster on an M2 than on an RTX 3070 using LibTorch). Calling `into_data` makes the times way more believable, but this creates a small overhead making the comparison not 100% fair, but at least the times were true.

**Comment by antimora** [comment]
Filed an issue with Candle team: https://github.com/huggingface/candle/issues/2050

**Pull request merged**
